image: node:latest

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

prepare:
  stage: build
  script: npm install

jest:
  stage: test
  needs: ['prepare']
  script:
    - npm run test
  allow_failure: true

pages:
  stage: deploy
  needs: ['prepare']
  script:
    - npm run build
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
  artifacts:
    expire_in: 1 day
    paths:
      - public
  only:
    - master
